_commit: v0.2.0
_src_path: https://github.com/gabriel-andreescu/BethesdaModKit.git
author: gabriel-andreescu
bmk_repository: https://github.com/gabriel-andreescu/BethesdaModKit.git
clib_util: false
components:
  - native
description: Disables the idle vanity camera.
devbench_api: false
devbench_tests: false
game: skyrim
native_settings: false
native_source: src
pack_assets: false
pre_commit: true
project_name: NoIdleVanityCameraSKSE
